#!/bin/sh

sed -n -e "s/CAMLprim value \([a-z0-9_][a-z0-9_]*\).*/\1/p" $(find ocamlrun -name '*.c') | sort | uniq > primitives
sed -n -e "s/^value  *\([a-z0-9_][a-z0-9_]*\).*/\1/p" $(find coqrun -name '*.c') | sort | uniq >> primitives

(echo '#include "mlvalues.h"'; \
 echo '#include "prims.h"'; \
 sed -e 's/.*/extern value &();/' primitives; \
 echo 'c_primitive caml_builtin_cprim[] = {'; \
 sed -e 's/.*/	&,/' primitives; \
 echo '	 0 };'; \
 echo 'char * caml_names_of_builtin_cprim[] = {'; \
 sed -e 's/.*/	"&",/' primitives; \
 echo '	 0 };') > ocamlrun/byterun/prims.c