(* DO NOT EDIT THIS FILE: automatically generated by ../configure *)

let local = false
let coqrunbyteflags = "-custom"
let coqlib = "./lib/coq"
let coqsrc = "."
let ocaml = "ocaml"
let ocamlc = "ocamlc"
let ocamlopt = "ocamlopt"
let ocamlmklib = "ocamlmklib"
let ocamldep = "ocamldep"
let ocamldoc = "ocamldoc"
let ocamlyacc = "ocamlyacc"
let ocamllex = "ocamllex"
let camlbin = "/usr/local/bin"
let camllib = "/usr/local/lib/ocaml"
let camlp4 = "camlp5"
let camlp4o = "camlp5o"
let camlp4bin = "/usr/local/bin"
let camlp4lib = "+camlp5"
let camlp4compat = "-loc loc"
let coqideincl = ""
let cflags = "-fno-defer-pop -Wall -Wno-unused"
let best = "byte"
let arch = "i386"
let has_coqide = "no"
let has_natdynlink = false
let natdynlinkflag = "false"
let osdeplibs = "-cclib -lunix"
let version = "8.3pl2"
let caml_version = "3.12.1"
let date = "December 2011"
let compile_date = "12 11 2011 08:29:34"
let vo_magic_number = 08300
let state_magic_number = 58300
let exec_extension = ""
let with_geoproof = ref false
let browser = "firefox -remote \"OpenURL(%s,new-tab)\" || firefox %s &"
let wwwcoq = "http://coq.inria.fr/"
let wwwrefman = wwwcoq ^ "distrib/" ^ version ^ "/refman/"
let wwwstdlib = wwwcoq ^ "distrib/" ^ version ^ "/stdlib/"
let localwwwrefman = "file://./share/doc/coq/html/refman/"

let theories_dirs = [
"Arith";
"Bool";
"Classes";
"FSets";
"Init";
"Lists";
"Logic";
"MSets";
"NArith";
"Numbers";
"Numbers/Cyclic";
"Numbers/Cyclic/Abstract";
"Numbers/Cyclic/DoubleCyclic";
"Numbers/Cyclic/Int31";
"Numbers/Cyclic/ZModulo";
"Numbers/Integer";
"Numbers/Integer/Abstract";
"Numbers/Integer/BigZ";
"Numbers/Integer/Binary";
"Numbers/Integer/NatPairs";
"Numbers/Integer/SpecViaZ";
"Numbers/NatInt";
"Numbers/Natural";
"Numbers/Natural/Abstract";
"Numbers/Natural/BigN";
"Numbers/Natural/Binary";
"Numbers/Natural/Peano";
"Numbers/Natural/SpecViaZ";
"Numbers/Rational";
"Numbers/Rational/BigQ";
"Numbers/Rational/SpecViaQ";
"Program";
"QArith";
"Reals";
"Relations";
"Setoids";
"Sets";
"Sorting";
"Strings";
"Structures";
"Unicode";
"Wellfounded";
"ZArith";
]
let plugins_dirs = [
"cc";
"dp";
"extraction";
"field";
"firstorder";
"fourier";
"funind";
"groebner";
"interface";
"micromega";
"nsatz";
"omega";
"quote";
"ring";
"romega";
"rtauto";
"setoid_ring";
"subtac";
"subtac/test";
"syntax";
"xml";
]
